name: Deploy Node Application

on:
  push:
      branches:
          - deployment-test

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source Code
              uses: actions/checkout@v4
            - name: Login to docker hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Build Docker Image Deployment Test
              run: docker build -t puthyporsk0108/book-rental-record-backend-test .
            - name: Publish Image to docker hub Deployment Test
              run: docker push puthyporsk0108/book-rental-record-backend-test:latest

    deploy:
        needs: build
        runs-on:  self-hosted
        steps:
            - name: Login to docker hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Pull image from docker hub Deployment Test
              run: docker pull puthyporsk0108/book-rental-record-backend-test:latest
            - name: Delete old container
              run: docker rm -f nodejs-app-container
            - name: Run Docker Container Deployment Test
              run: docker run -d -p 5000:5000 --name nodejs-app-container -e MONGO_URL='${{ secrets.MONGO_URL_TEST }}' puthyporsk0108/book-rental-record-backend-test
            - name: Delete old image
              run: docker system prune -f
